name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Setup .NET environment
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Passe die Version an dein Projekt an
      
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./src/BaseApiStuff/BaseApiStuff.csproj
      
      # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore ./src/BaseApiStuff/BaseApiStuff.csproj
      
      # Pack the library
      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build --output ./nupkgs ./src/BaseApiStuff/BaseApiStuff.csproj
      
      # Push to GitHub Package Registry
      - name: Publish NuGet Package
        run: dotnet nuget push "./nupkgs/*.nupkg" --source "github" --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
